version: "3.8"

services:
  web:
    build: ./django
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 tracker.asgi:application"
    volumes:
      - ./django:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  frontend:
    build: ./frontend/myapp
    volumes:
      - ./frontend/myapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pricetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
