version: "3.8"

services:
  web:
    build: ./django
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 tracker.asgi:application"
    volumes:
      - ./django:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - redpanda
    env_file:
      - .env

  frontend:
    build: ./frontend/myapp
    volumes:
      - ./frontend/myapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pricetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.10
    container_name: redpanda
    ports:
      - "9092:9092"
    command: >
      redpanda start
      --overprovisioned
      --smp 1
      --memory 1G
      --reserve-memory 0M
      --node-id 0
      --check=false
      --advertise-kafka-addr redpanda:9092

  celery-worker:
    build: ./django
    command: celery -A tracker worker --loglevel=info
    volumes:
      - ./django:/app
    depends_on:
      - web
      - redis
      - redpanda
    env_file:
      - .env

  celery-beat:
    build: ./django
    command: celery -A tracker beat --loglevel=info
    volumes:
      - ./django:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
