# Generated by Django 5.2.4 on 2025-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedproduct',
            name='product_url',
            field=models.URLField(max_length=1500),
        ),
    ]
